version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./html:/usr/local/nginx/html
      - ./nginx/logs:/var/log/nginx
      - ./nginx/cache:/var/cache/nginx
    links:
      - netease-music-api
    restart: always
  netease-music-api:
    image: netease-music-api
    expose:
      - "3000"
